### PR TITLE
Use standalone ActiveAQ in claw_vagrant; Resolves https://github.com/…

### PR DESCRIPTION
**Pull request by ruebot**
**GitHub Issue**: https://github.com/Islandora-CLAW/CLAW/issues/660

# What does this Pull Request do?

Adds a standalone ActiveMQ instance, and a bit of documentation. Also cleans up a little cruft I noticed. 

# What's new?
Standalone ActiveMQ

# How should this be tested?

1. `git clone -b issue-660 https://github.com/yorkulibraries/claw_vagrant.git`
2. `cd claw_vagrant`
3. `vagrant up`
4. :coffee: or :tumbler_glass: or :coffee::heavy_plus_sign::tumbler_glass:
5. `vagrant ssh`
6. `/opt/karaf/bin/client`
7. `log:tail`
8. http://localhost:8161/admin/ (admin admin)
9. Add an Islandora Collection node and keep and eye on Karaf log
10. Verify you see the node sync'd to fcrepo
11. :balloon: 

Here are some screenshots:

screenshot from 2017-06-09 13-04-07
screenshot from 2017-06-09 13-03-04
screenshot from 2017-06-09 13-10-27
screenshot from 2017-06-09 13-03-50

# Interested parties
@whikloj @dannylamb @ajs6f @jonathangreen

### CODE REVIEW

**Review by ajs6f — APPROVED** [review]
You did it!

**Comment by ajs6f** [comment]
After this is in, we might make a follow-on ticket for moving the AMQ instance inside Karaf. I know there are some [complications](https://issues.apache.org/jira/browse/CAMEL-10405) with that, but time will solve those problems if we don't first.

**Comment by dannylamb** [comment]
`vagrant up`

**Comment by dannylamb** [comment]
<image src="http://i.imgur.com/urr7Za0.gif" />

Works as intended.  I hope this puts the activemq issue to bed once and for all.  Thanks @ruebot.

:shipit:

**Review by dannylamb — APPROVED** [review]

**Pull request merged**
