### PR TITLE
Removes Amherst extensions specified in CLAW issue 613

### PR DESCRIPTION
**Pull request by bryjbrown**
**GitHub Issue**: https://github.com/Islandora-CLAW/CLAW/issues/613

# What does this Pull Request do?
Deletes lines from config scripts related to Amherst stuff

# What's new?
Nothing new, just less old stuff.

# How should this be tested?
See if it builds? I ran it through a build and created a test resource with no errors.

# Interested parties
@dannylamb

### CODE REVIEW

**Comment by whikloj** [comment]
Looks good @bryjbrown, if @dannylamb doesn't get to this tonight. I'll spin it up tomorrow but I think it should be 👍

**Comment by whikloj** [comment]
`vagrant up`

**Comment by dannylamb** [comment]
I wouldn't be able to get to this until later this afternoon.  I'll trust @whikloj's judgement on this one.

**Review by whikloj — APPROVED** [review]
Totally lost track of this, it came up and the microservices seem to be up. I was able to push stuff to fedora with Milliner, etc.

**Pull request merged**
