### PR TITLE
Issue 640

### PR DESCRIPTION
**Pull request by dannylamb**
**GitHub Issue**: Install for Islandora-CLAW/CLAW#640

* See also Islandora-Devops/claw-playbook#21

# What does this Pull Request do?

Install updates for Islandora-CLAW/CLAW#640

# What's new?

* Updates Gemini schema for MySQL
* Adds config for filehash module
* Adds REST resources (formerly done in islandora module's install hook)

# How should this be tested?

You need to point to my forks for Alpaca and Crayfish.  You also need to skip the drupal config import until after you have updated the modules.  You can follow along or just scrape out this patch and apply it directly:
```diff
diff --git a/scripts/alpaca.sh b/scripts/alpaca.sh
index 26abc19..3ecd592 100755
--- a/scripts/alpaca.sh
+++ b/scripts/alpaca.sh
@@ -9,7 +9,7 @@ if [ -f "$HOME_DIR/islandora/configs/variables" ]; then
 fi
 
 cd "$HOME_DIR"
-git clone https://github.com/Islandora-CLAW/Alpaca.git
+git clone -b issue-640 https://github.com/dannylamb/Alpaca.git
 cd Alpaca
 chown -R ubuntu:ubuntu "$HOME_DIR/Alpaca"
 sudo -u ubuntu ./gradlew install
diff --git a/scripts/crayfish.sh b/scripts/crayfish.sh
index 7800649..98548c9 100755
--- a/scripts/crayfish.sh
+++ b/scripts/crayfish.sh
@@ -9,7 +9,7 @@ if [ -f "$HOME_DIR/islandora/configs/variables" ]; then
 fi
 
 cd /var/www/html
-git clone https://github.com/Islandora-CLAW/Crayfish.git
+git clone -b issue-640 https://github.com/dannylamb/Crayfish.git
 cd Crayfish
 
 for D in */; do
diff --git a/scripts/drupal.sh b/scripts/drupal.sh
index a58f186..a33e765 100755
--- a/scripts/drupal.sh
+++ b/scripts/drupal.sh
@@ -137,4 +137,4 @@ usermod -a -G www-data ubuntu
 mkdir "$HOME_DIR/auth"
 openssl genrsa -out "$HOME_DIR/auth/private.key" 2048
 openssl rsa -pubout -in "$HOME_DIR/auth/private.key" -out "$HOME_DIR/auth/public.key"
-$DRUSH_CMD config-import -y --partial --source="$HOME_DIR/islandora/configs/drupal/"
+#$DRUSH_CMD config-import -y --partial --source="$HOME_DIR/islandora/configs/drupal/"
```

Then `vagrant up`.

Once it's done, you need to run [this gist](https://gist.githubusercontent.com/dannylamb/9bf360d63e8c4a829ff72b75faba2264/raw/6020d83dc514748a9df9ade26c6790cebff3b47f/issue-640.sh) to update and install the islandora modules from my forks.  You can `vagrant ssh` into the box and do so with:
```
curl https://gist.githubusercontent.com/dannylamb/9bf360d63e8c4a829ff72b75faba2264/raw/6020d83dc514748a9df9ade26c6790cebff3b47f/issue-640.sh | sudo bash
```

Then you can test the box by adding and removing content, and checking that it is accurately reflected in Fedora and the triplestore.

If you find yourself wading through a lot of exceptions in Karaf logs from Api-X, see [this workaround](https://github.com/fcrepo4-labs/fcrepo-api-x/issues/149#issuecomment-339011500) until we can sort it out on a separate issue.

# Interested parties
@Islandora-CLAW/committers

### CODE REVIEW

**Comment by MarcusBarnes** [comment]
I tried following the directions for testing this pull request.  After creating some content, I noticed that content is pushed to Fedora, but the details are not pushed to the triplestore.  Upon inspecting the ActiveMQ queues,  there appears to be 0 consumers for the `islandora-indexing-triplestore` queue.  The number of pending messages for this queue match number of new content I created.

**Comment by dannylamb** [comment]
@MarcusBarnes Is the box still laying around?  Can you `la | grep islandora` from the karaf console and tell me if the bundle is 'Active'?

**Comment by MarcusBarnes** [comment]
@dannylamb The output from `la | grep islandora` from within the Karaf console indicates that  `islandora-indexing-triplestore` is Active.

**Comment by whikloj** [comment]
@dannylamb The config for the islandora-indexing-triplestore feature indicates a change from one queue to two (https://github.com/Islandora-CLAW/Alpaca/pull/48/files#diff-d6faeeeee8e4b65be5a42765db3ed169) but the broadcaster is still routing to the old queue (` IslandoraBroadcastRecipients=activemq:queue:islandora-indexing-fcrepo-content,activemq:queue:islandora-indexing-triplestore`) and I can't see what is supposed to route the messages (based I am guessing on EventType)

**Review by whikloj — APPROVED** [review]
👍

**Comment by seth-shaw-unlv** [comment]
Tested this out today and it appears to work. However, deleting an Islandora Image did not delete the associated media. Are we not cascading these deletes?

**Comment by whikloj** [comment]
@seth-shaw-unlv it does but the file is not deleted from Drupal until a cron run. You can see instructions in the claw-playbook PR to make the cron run quicker.
https://github.com/Islandora-Devops/claw-playbook/pull/21

**Comment by whikloj** [comment]
@seth-shaw-unlv I also forgot that deleting the islandora image does **not** remove the Drupal media element. So if you go under Content -> Media, you can remove the Media element and **them** the file should be free to get cleaned up.

**Pull request merged**
