### PR TITLE
Adjust paths for vagrant scripts

### PR DESCRIPTION
**Pull request by whikloj**

### CODE REVIEW

**Comment by whikloj** [comment]
👍  ok but now we need someone else to test this out. @DiegoPino @dannylamb @kimpham54 @MarcusBarnes @Natkeeran @bryjbrown 

By test this out, I mean.
1. Clone the https://github.com/ruebot/claw_vagrant repo (master branch)
2. cd into your new claw_vagrant directory
3. run `vagrant up`
4. Make sure it comes up and you can create a new Drupal content Fedora Resource

**Comment by MarcusBarnes** [comment]
I'll test.  Thank you.

**Comment by MarcusBarnes** [comment]
My initial test appears to work as expected.   Are there any specific things I should be looking for when testing?

**Comment by bryjbrown** [comment]
Also giving it a test. It is `vagrant up`ing now.

**Comment by MarcusBarnes** [comment]
I added my repo oauth token in the appropriate location in the `configs/variables` file.  Was this needed?

**Comment by bryjbrown** [comment]
Young Frankenstein

It came up just fine, and has the ability to create Fedora Resources! 👍

**Comment by whikloj** [comment]
@MarcusBarnes weird, I didn't set my OAuth token and it seemed to work 😕

**Comment by MarcusBarnes** [comment]
It wasn't in the directions above - I set it when looking at the old documentation in the README before my test.  So it may not be necessary.

**Comment by dannylamb** [comment]
I'd add it anyway to be safe.  Whether or not you get throttled by Github is up to them, Composer, and the phases of the moon.  With the token it's guaranteed to work.

**Comment by dannylamb** [comment]
@ruebot np

**Pull request merged**
